import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {DataProvider} from "@/context/authContext"
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-[var(--background)] text-[var(--foreground)] antialiased">
      <body className="bg-[var(--background)] text-[var(--foreground)]">

        <DataProvider>
          {/* Main Content */}
          <main className="flex-1 bg-[var(--background)] overflow-y-auto">
            <ToastContainer
              position="top-right"
              autoClose={1500}
              hideProgressBar={true}
              newestOnTop={false}
              closeOnClick={true}
              rtl={false}
              pauseOnHover
              theme="light"
            />
            <section className="space-y-3">
              {children}
            </section>
          </main>
        </DataProvider>

      </body>
    </html>
  );
}
